// types/custom.d.ts
// Canonical home for manual ambient type declarations.
// next-env.d.ts is auto-generated by Next.js and must NOT be edited manually.

// CSS Modules — typed shape so class names resolve to string, not any.
declare module "*.css" {
  const styles: { [className: string]: string };
  export default styles;
}

// SVG imports via @svgr/webpack or next-svgr — resolves as a React component.
declare module "*.svg" {
  import type React from "react";
  const ReactComponent: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default ReactComponent;
}
